### ISSUE TITLE
Fatal: unable to connect

### ISSUE THREAD

**Issue by karellm** [applicationsonline/librarian#100]
Hi,

I get a fatal error when I try to `librarian-chef install` the following `Cheffile`:

```
#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# common software
cookbook 'apt'
cookbook 'openssl'
cookbook 'vim'
cookbook 'git'
cookbook 'byobu', :git => 'https://github.com/karellm/cookbook-byobu'

# custom vm config
cookbook 'vmconfig', :git => 'git://gitolite@xx.xx.xx.xx:cookbook-vmconfig.git' # I hid the ip

# servers
cookbook 'apache2'

# databases
cookbook 'mysql'

# programming languages
cookbook 'php'
```

I get the following error:

```
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:205:in `block in run_command_internal': fatal: unable to connect to : (StandardError)
[0: ::1]: errno=Connection refused
[1: 127.0.0.1]: errno=Connection refused

    from /Users/me/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
    from /Users/me/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open3.rb:90:in `popen3'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:204:in `run_command_internal'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:156:in `block (2 levels) in run!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:188:in `logging_command'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:155:in `block in run!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:163:in `block (2 levels) in maybe_within'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:173:in `with_env_var'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:163:in `block in maybe_within'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:163:in `chdir'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:163:in `maybe_within'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:154:in `run!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git/repository.rb:75:in `clone!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/git.rb:97:in `cache!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/local.rb:31:in `manifest_search_paths'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/source/local.rb:40:in `found_path'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/chef/source/local.rb:58:in `expect_manifest!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/chef/source/local.rb:46:in `fetch_manifest_data'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/chef/source/local.rb:42:in `manifest_data'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/chef/source/local.rb:26:in `fetch_version'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/manifest.rb:117:in `fetch_version!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/manifest.rb:109:in `fetched_version'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/manifest.rb:63:in `version'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/manifest.rb:93:in `satisfies?'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/dependency.rb:69:in `satisfied_by?'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:69:in `block (5 levels) in recursive_resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:69:in `each'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:69:in `all?'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:69:in `block (4 levels) in recursive_resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:107:in `scope'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:68:in `block (3 levels) in recursive_resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:64:in `each'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:64:in `block (2 levels) in recursive_resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:107:in `scope'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:63:in `block in recursive_resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:107:in `scope'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:46:in `recursive_resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver/implementation.rb:24:in `resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/resolver.rb:19:in `resolve'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/action/resolve.rb:25:in `run'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/cli.rb:164:in `resolve!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/chef/cli.rb:41:in `install'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/lib/librarian/cli.rb:33:in `bin!'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/gems/librarian-0.0.24/bin/librarian-chef:7:in `<top (required)>'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/bin/librarian-chef:19:in `load'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/bin/librarian-chef:19:in `<main>'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/me/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

Do you know what is going on? I have a local ssh key that authenticate me on gitolite to RW the repo and a `git clone gitolite@xx.xx.xx.xx:cookbook-vmconfig.git` works.

**Comment by piousbox** [comment]
Same problem here.

**Comment by databus23** [comment]
Try removing the git:// prefix in the Cheffile for that repo.

**Comment by karellm** [comment]
I switched to berks so I can't run the test but from what I remember, that wouldn't work without the git:// as it tries to get it using http and I haven't installed the http plugin for git on my server (only ssh is available).

**Comment by yfeldblum** [comment]
The error is coming from `git`, which is being shelled out to.

Is there a way to replicate this elsewhere, without setting up gitolite?
