### ISSUE TITLE
Unable to specify github cookbook

### ISSUE THREAD

**Issue by greenmoss** [applicationsonline/librarian#103]
I am having a similar problem as [issue 94](https://github.com/applicationsonline/librarian/issues/94) (dies with "No metadata file found"). The suggested fix using :path doesn't work for me:

```
cookbook 'graphite',
  :git => 'https://github.com/greenmoss/chef-graphite',
  :path => 'graphite'
```

Error stack:

```
[Librarian] Running `/opt/local/bin/git clone https://github.com/greenmoss/chef-graphite . --
quiet` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --- No output
[Librarian] Running `/opt/local/bin/git reset --hard --quiet` in tmp/librarian/cache/source/g
it/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --- No output
[Librarian] Running `/opt/local/bin/git clean -x -d --force --force` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --- No output
[Librarian] Running `/opt/local/bin/git rev-parse HEAD --quiet` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --> 4032ee415abd340d0f7adf3ab8ebe55d9b58b879
[Librarian] Running `/opt/local/bin/git fetch origin --quiet` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --- No output
[Librarian] Running `/opt/local/bin/git fetch origin --quiet --tags` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --- No output
[Librarian] Running `/opt/local/bin/git remote` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --> origin
[Librarian] Running `/opt/local/bin/git branch -r` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/master
[Librarian]     -->   origin/sentry
[Librarian] Running `/opt/local/bin/git rev-list origin/master -1` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --> d3fe1ab86dfda965fe7f1b031cd23dda9d1325f9
[Librarian] Running `/opt/local/bin/git rev-parse HEAD --quiet` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --> 4032ee415abd340d0f7adf3ab8ebe55d9b58b879
[Librarian] Running `/opt/local/bin/git checkout d3fe1ab86dfda965fe7f1b031cd23dda9d1325f9 --quiet` in tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --- No output
[Librarian] Running `/opt/local/bin/git rev-parse HEAD --quiet` in chef-repo/tmp/librarian/cache/source/git/88bf306cc22d760b41f474fc56a573e9
[Librarian]     --> d3fe1ab86dfda965fe7f1b031cd23dda9d1325f9
No metadata file found for graphite from https://github.com/greenmoss/chef-graphite#master(graphite)! If this should be a cookbook, you might consider contributing a metadata file upstream or forking the cookbook to add your own metadata file.
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/chef/source/local.rb:63:in `expect_manifest!'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/chef/source/local.rb:48:in `fetch_manifest_data'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/chef/source/local.rb:44:in `manifest_data'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/chef/source/local.rb:28:in `fetch_version'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/manifest.rb:109:in `fetch_version!'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/manifest.rb:101:in `fetched_version'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/manifest.rb:55:in `version'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/manifest.rb:51:in `to_s'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:77:in `recursive_resolve'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:123:in `debug'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/logger.rb:31:in `debug'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/ui.rb:32:in `debug'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/logger.rb:31:in `debug'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:123:in `debug'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:77:in `recursive_resolve'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:74:in `each'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:74:in `recursive_resolve'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:117:in `scope'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:73:in `recursive_resolve'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:117:in `scope'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:56:in `recursive_resolve'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver/implementation.rb:30:in `resolve'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/resolver.rb:18:in `resolve'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/action/resolve.rb:25:in `run'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/cli.rb:171:in `resolve!'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/chef/cli.rb:41:in `install'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/task.rb:27:in `send'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
/opt/local/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/cli.rb:28:in `bin!'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/cli.rb:45:in `with_environment'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/lib/librarian/cli.rb:26:in `bin!'
/opt/local/lib/ruby/gems/1.8/gems/librarian-0.0.25/bin/librarian-chef:7
/opt/local/bin/librarian-chef:19:in `load'
/opt/local/bin/librarian-chef:19
```

**Comment by yfeldblum** [comment]
You can't use the `:path =>` option here because the cookbook is in the root of the git repository, not in a subdirectory. The `:path =>` option on a git source tells Librarian-Chef where within the git repository to look for the cookbook in question.
