### ISSUE TITLE
site_spec failures: Cheffile and Cheffile.lock are out of sync!

### ISSUE THREAD

**Issue by taqtiqa-mark** [applicationsonline/librarian#107]
Adding another source, e.g. duplicating `site` under another name, triggers errors in `site_spec`

Running:

```
~/.rbenv/versions/1.9.2-p290/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /src/3rdparty/librarian/bin/rspec /src/3rdparty/librarian/spec/functional/chef/source/site_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter
```

I see:

```
11 examples, 7 failures, 4 passed
```

The failures are like this example:

```
Librarian::Error: Cheffile and Cheffile.lock are out of sync!
/src/3rdparty/librarian/lib/librarian/action/install.rb:32:in `check_consistent'
/src/3rdparty/librarian/lib/librarian/action/install.rb:20:in `check_preconditions'
/src/3rdparty/librarian/lib/librarian/action/install.rb:10:in `run'
/src/3rdparty/librarian/spec/functional/chef/source/site_spec.rb:170:in `block (5 levels) in <module:Source>'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:236:in `instance_eval'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:236:in `instance_eval'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:23:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:72:in `block in run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:72:in `each'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:72:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:424:in `run_hook'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:323:in `run_before_each_hooks'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:299:in `run_before_each'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:112:in `block in run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:253:in `with_around_each_hooks'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:110:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:378:in `block in run_examples'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in `map'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in `run_examples'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:360:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `block in run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `map'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `block in run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `map'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `block in run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `map'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:361:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `map'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block in run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/reporter.rb:34:in `report'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:25:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
```

**Comment by yfeldblum** [comment]
[Not that I'm aware of.](https://travis-ci.org/#!/applicationsonline/librarian)

**Comment by yfeldblum** [comment]
You may have a `Cheffile` somewhere up the filesystem tree from the `tmp/spec/chef/site-source` relative to the project root.

Or you may be running the specs from a directory other than the project root.

**Comment by yfeldblum** [comment]
These action classes such as `Librarian::Action::Install` may be searching up the tree from `Dir.pwd` up to the filesystem root looking for a `Cheffile`.

**Comment by taqtiqa-mark** [comment]
Actually it can be triggered in this way:

Duplicate the chef/source/site as `site_b`, i.e. add this to the `dsl.rb` and `source.rb` files.

The originial `site_spec.rb` should now fail as above.

comment out `site_b` from the dsl and source files and `site_spec.rb` should pass again.

**Comment by taqtiqa-mark** [comment]
With duplicated `Librarian::Chef::Source::Site` class as `Librarian::Chef::Source::Ckbks`, that is emptied, it seems `Action::Resolve.new(env).run` does some sort of recursive lookup on all files loaded from `chef/source.rb`. So far:

```
expected no Exception, got #<NoMethodError: undefined method `lock_name' for Librarian::Chef::Source::Ckbks:Class>
/src/3rdparty/librarian/vendor/gems/rspec-expectations-2.11.3/lib/rspec/expectations/fail_with.rb:33:in `fail_with'
/src/3rdparty/librarian/vendor/gems/rspec-expectations-2.11.3/lib/rspec/expectations/handler.rb:42:in `handle_matcher'
/src/3rdparty/librarian/vendor/gems/rspec-expectations-2.11.3/lib/rspec/expectations/expectation_target.rb:48:in `to_not'
/src/3rdparty/librarian/spec/functional/chef/source/site_spec.rb:93:in `block (5 levels) in <module:Source>'
/src/3rdparty/librarian/vendor/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:113:in `instance_eval'
```

@yfeldblum, any hints on where `Action::Resolve.new(env).run` behavior is spec'd, even indirectly?

**Comment by flatrocks** [comment]
You can also trigger the "out of sync!" message with this sort of thing in the Cheffile:

```
cookbook 'cookbook1', path: './site-cookbooks/cookbook1'
cookbook 'cookbook1', path: './site-cookbooks/cookbook2'
```

While mine was an obvious "cut and paste" error, it was made more difficult to track down due to the misleading error message.

**Comment by taqtiqa-mark** [comment]
No longer using Librarian.
