### ISSUE TITLE
Java Cookbook causes tsort error

### ISSUE THREAD

**Issue by farmdawgnation** [applicationsonline/librarian#160]
I'm seeing the following error when I attempt to use librarian-chef to install the java cookbook. I wasn't entirely sure where to file the bug, but under the thesis that no cookbook should trigger an error like this, I decided to file it here. Let me know what else I can do to help.

```
/Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:228:in `block in tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/manifest_set.rb:11:in `each'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:411:in `call'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each_key'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `call'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:175:in `tsort'
    from /Users/matt/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:150:in `tsort'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/manifest_set.rb:31:in `sort'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/resolver.rb:73:in `sort'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/resolver.rb:19:in `resolve'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/action/resolve.rb:26:in `run'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/cli.rb:169:in `resolve!'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-chef-0.0.2/lib/librarian/chef/cli.rb:41:in `install'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/cli.rb:31:in `returning_status'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `block in bin!'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/cli.rb:47:in `with_environment'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `bin!'
    from /Users/matt/.rvm/gems/ruby-2.1.0/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from /Users/matt/.rvm/gems/ruby-2.1.0/bin/librarian-chef:23:in `load'
    from /Users/matt/.rvm/gems/ruby-2.1.0/bin/librarian-chef:23:in `<main>'
    from /Users/matt/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/matt/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by farmdawgnation** [comment]
I've also confirmed this error in ruby 1.9.3, btw.

**Comment by yfeldblum** [comment]
Closing this issue in favor of #159, which includes this issue. Thanks! There is a cyclic dependency between two cookbooks your Cheffile depends on.
