### ISSUE TITLE
Call to fork results in error on windows

### ISSUE THREAD

**Issue by dkingofpa** [applicationsonline/librarian#34]
I'm trying to use librarian on windows.  When it tries to download a cookbook from the community site, it calls "fork" and gives an error:

```
[Librarian] Installing apache2/1.0.8 <http://community.opscode.com/api/v1>
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/apache2/versions/1_0_8
c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/chef/source/site.rb:180:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/chef/source/site.rb:180:in `cache_version_package!'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/chef/source/site/manifest.rb:73:in `fetch_version_manifest!'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/chef/source/site/manifest.rb:69:in `version_manifest'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/chef/source/site/manifest.rb:80:in `install!'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/action/install.rb:55:in `block in install_manifests'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/action/install.rb:54:in `each'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/action/install.rb:54:in `install_manifests'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/action/install.rb:40:in `perform_installation'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/action/install.rb:12:in `run'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/cli.rb:113:in `install!'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/cli.rb:68:in `install'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/lib/librarian/cli.rb:27:in `bin!'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/librarian-0.0.12/bin/librarian-chef:7:in `<top (required)>'
        from c:/Ruby192/bin/librarian-chef:19:in `load'
        from c:/Ruby192/bin/librarian-chef:19:in `<main>'
```

I've tried the win32-process gem with no success.
https://rubygems.org/gems/win32-process

I may be able to avoid this issue by suggesting cygwin as a solution, but still wanted to get this on the radar.

**Comment by dkingofpa** [comment]
I've confirmed that librarian works on windows via cygwin.  That's a viable workaround for me.

**Comment by yfeldblum** [comment]
It is not viable for me to get Librarian working on Windows proper at this time.

But you have confirmed using cygwin is a workaround, so I have to close this issue.

If someone wants to contribute proper Windows support, that would certainly be helpful.
