### ISSUE TITLE
librarian-chef install fails with multiple remote branches

### ISSUE THREAD

**Issue by bradmontgomery** [applicationsonline/librarian#49]
I just ran into this issue. Here's what I did:
- Edit Cheffile
- Add a cookbook referencing a github repo
- ran `librarian-chef install` 

This resulted in the following:

```
/Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:102:in `block in run!': StandardError
from /Users/brad/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
from /Users/brad/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open3.rb:90:in `popen3'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:101:in `run!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:62:in `block in merge!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:110:in `block in within'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:110:in `chdir'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:110:in `within'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:60:in `merge!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:83:in `block in merge_all_remote_branches!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:81:in `each'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:81:in `merge_all_remote_branches!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git.rb:85:in `cache!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/dependency.rb:31:in `cache_manifests!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/dependency.rb:27:in `manifests'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:49:in `block in recursive_resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:102:in `scope'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:36:in `recursive_resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:21:in `resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver.rb:18:in `resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/action/resolve.rb:25:in `run'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/cli.rb:117:in `resolve!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/cli.rb:67:in `install'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/cli.rb:27:in `bin!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/bin/librarian-chef:7:in `<top (required)>'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/bin/librarian-chef:19:in `load'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/bin/librarian-chef:19:in `<main>'
```

Immediately re-running `librarian-chef install` yielded:

```
/Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:102:in `block in run!': fatal: 'merge' is not possible because you have unmerged files. (StandardError)
Please, fix them up in the work tree, and then use 'git add/rm <file>' as appropriate to mark resolution and make a commit, or use 'git commit -a'.
from /Users/brad/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
from /Users/brad/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open3.rb:90:in `popen3'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:101:in `run!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:62:in `block in merge!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:110:in `block in within'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:110:in `chdir'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:110:in `within'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:60:in `merge!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:83:in `block in merge_all_remote_branches!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:81:in `each'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git/repository.rb:81:in `merge_all_remote_branches!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/source/git.rb:85:in `cache!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/dependency.rb:31:in `cache_manifests!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/dependency.rb:27:in `manifests'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:49:in `block in recursive_resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:102:in `scope'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:36:in `recursive_resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver/implementation.rb:21:in `resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/resolver.rb:18:in `resolve'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/action/resolve.rb:25:in `run'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/cli.rb:117:in `resolve!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/cli.rb:67:in `install'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/lib/librarian/cli.rb:27:in `bin!'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/gems/librarian-0.0.14/bin/librarian-chef:7:in `<top (required)>'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/bin/librarian-chef:19:in `load'
from /Users/brad/.rvm/gems/ruby-1.9.3-p125@chef-coroutine/bin/librarian-chef:19:in `<main>'
```

It turns out this repo had multiple remote branches, and deleting everything but `origin/master` allowed me to successfully run `librarian-chef install`.

I'm not sure if this is related to Issue #44, but if it is, please feel free to act accordingly.

Thanks!

**Comment by yfeldblum** [comment]
Is your issue resolved with librarian master?
