### ISSUE TITLE
Validate Rubygems Version

### ISSUE THREAD

**Issue by nstielau** [applicationsonline/librarian#53]
Hey,

Just getting started with Librarian, and ran into some weird issues: https://gist.github.com/de43e3ba429f967f31bf

Turns out, my Rubygems was out of date (1.3.6, yeah, I don't get out much).  It would be awesome if Librarian could validate the rubygems version and error out with a simple error message for unsupported versions.  Or, it could be specified in the gemspec itself.  

Thanks!

**Comment by yfeldblum** [comment]
Which version of rubygems worked for you?

**Comment by nstielau** [comment]
Just upgraded to the latest, 1.8.21.  I was at 1.3.7, which didn't work, seemingly due to some version comparison issue.

```
/Library/Ruby/Site/1.8/rubygems/requirement.rb:15:in `>=': comparison of Librarian::Manifest::Version with Gem::Version failed (ArgumentError)
        from /Library/Ruby/Site/1.8/rubygems/requirement.rb:15
        from /Library/Ruby/Site/1.8/rubygems/requirement.rb:134:in `call'
        from /Library/Ruby/Site/1.8/rubygems/requirement.rb:134:in `satisfied_by?'
        from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `all?'
        from /Library/Ruby/Site/1.8/rubygems/requirement.rb:134:in `each'
        from /Library/Ruby/Site/1.8/rubygems/requirement.rb:134:in `all?'
        from /Library/Ruby/Site/1.8/rubygems/requirement.rb:134:in `satisfied_by?'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/manifest.rb:71:in `satisfies?'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/dependency.rb:36:in `satisfied_by?'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:58:in `recursive_resolve'
        from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `all?'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:58:in `each'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:58:in `all?'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:58:in `recursive_resolve'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:102:in `scope'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:57:in `recursive_resolve'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:54:in `each'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:54:in `recursive_resolve'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:102:in `scope'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:53:in `recursive_resolve'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:102:in `scope'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:36:in `recursive_resolve'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver/implementation.rb:21:in `resolve'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/resolver.rb:18:in `resolve'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/action/resolve.rb:25:in `run'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/cli.rb:117:in `resolve!'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/cli.rb:67:in `install'
        from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
        from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
        from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/lib/librarian/cli.rb:27:in `bin!'
        from /Library/Ruby/Gems/1.8/gems/librarian-0.0.15/bin/librarian-chef:7
        from /usr/bin/librarian-chef:19:in `load'
        from /usr/bin/librarian-chef:19
```

**Comment by nstielau** [comment]
P.S. Wow, librarian is amazing, it makes Chef usable. agoddard and mattray pitched it at DevOpsDays Austin, and I'm hooking it up for the Graylog2 chef cookbook repo for managing dependencies. Cheers!
