### ISSUE TITLE
Permission denied on `librarian-chef install` on Windows since v0.0.21

### ISSUE THREAD

**Issue by tknerr** [applicationsonline/librarian#68]
Hello,

I'm using librarian-chef on a Windows 7 64Bit box. Starting with v0.0.21 I now get the following error on `librarian-chef install`:

```
W:\repo\my-chef-repo>librarian-chef install
W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:519:in `rename': Permission denied - (C:/Users/tkn/AppData/Local/Temp/apache2, W:/repo/my-chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/apache2/version-uri/3c9da46c37b6c22c7005d34bd6bc6df9/package) (Errno::EACCES)
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:519:in `block in mv'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:508:in `mv'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/chef/source/site.rb:241:in `cache_version_uri_unpacked!'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/chef/source/site.rb:225:in `cache_version_unpacked!'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/chef/source/site.rb:35:in `install_version!'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/chef/source/site.rb:374:in `install!'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/manifest.rb:97:in `install!'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/action/install.rb:56:in `block in install_manifests'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/action/install.rb:55:in `each'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/action/install.rb:55:in `install_manifests'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/action/install.rb:40:in `perform_installation'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/action/install.rb:12:in `run'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/cli.rb:130:in `install!'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/cli.rb:70:in `install'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/task.rb:27:in `run'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/invocation.rb:120:in `invoke_task'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor.rb:275:in `dispatch'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/base.rb:408:in `start'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/lib/librarian/cli.rb:29:in `bin!'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/librarian-0.0.21/bin/librarian-chef:7:in `<top (required)>'
        from W:/tools/vagrant/embedded/bin/librarian-chef:19:in `load'
        from W:/tools/vagrant/embedded/bin/librarian-chef:19:in `<main>'
```

**Comment by yfeldblum** [comment]
I pushed 27fb894957bf9333461c1f27aff50cd12ddc9697.

Can you check if this is fixed in the current master, and let me know if this is still a problem?

```
git clone https://github.com/applicationsonline/librarian
/path/to/clone/of/librarian/bin/librarian-chef install --verbose
```

**Comment by tknerr** [comment]
Still the same issue :-(

```
W:\repo\my-chef-repo>ruby D:\Repos\_github\librarian\bin\librarian-chef install --verbose
[Librarian] Pre-Cached Sources:
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian]   [:path, "../my-cookbooks/vagrant-ohai", {}]
[Librarian] Post-Cached Sources:
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian]   [:path, "../my-cookbooks/vagrant-ohai", {}]
[Librarian] The specfile is unchanged: nothing to do.
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian]   [:path, "../my-cookbooks/vagrant-ohai", {}]
[Librarian] Installing apache2/1.1.8 <http://community.opscode.com/api/v1>
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/apache2 to W:/repo/my-chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/apache2/metadata.json
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/apache2/versions/1_1_8 to W:/repo/my-chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/apache2/version-uri/3c9da46c37b6c22c7005d34bd6bc6df9/metadata.json
[Librarian] Caching http://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/1558/original/apache2.tgz?1335395352 to W:/repo/my-chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/apache2/version-uri/3c9da46c37b6c22c7005d34bd6bc6df9/package.tar.gz
W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:519:in `rename': Permission denied - (C:/Users/tkn/AppData/Local/Temp/d20120511-4676-okqrau/apache2, W:/repo/my-chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/apache2/version-uri/3c9da46c37b6c22c7005d34bd6bc6df9/package) (Errno::EACCES)
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:519:in `block in mv'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/fileutils.rb:508:in `mv'
        from D:/Repos/_github/librarian/lib/librarian/chef/source/site.rb:291:in `block in unpack!'
        from W:/tools/vagrant/embedded/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
        from D:/Repos/_github/librarian/lib/librarian/chef/source/site.rb:285:in `unpack!'
        from D:/Repos/_github/librarian/lib/librarian/chef/source/site.rb:237:in `cache_version_uri_unpacked!'
        from D:/Repos/_github/librarian/lib/librarian/chef/source/site.rb:225:in `cache_version_unpacked!'
        from D:/Repos/_github/librarian/lib/librarian/chef/source/site.rb:35:in `install_version!'
        from D:/Repos/_github/librarian/lib/librarian/chef/source/site.rb:384:in `install!'
        from D:/Repos/_github/librarian/lib/librarian/manifest.rb:97:in `install!'
        from D:/Repos/_github/librarian/lib/librarian/action/install.rb:56:in `block in install_manifests'
        from D:/Repos/_github/librarian/lib/librarian/action/install.rb:55:in `each'
        from D:/Repos/_github/librarian/lib/librarian/action/install.rb:55:in `install_manifests'
        from D:/Repos/_github/librarian/lib/librarian/action/install.rb:40:in `perform_installation'
        from D:/Repos/_github/librarian/lib/librarian/action/install.rb:12:in `run'
        from D:/Repos/_github/librarian/lib/librarian/cli.rb:130:in `install!'
        from D:/Repos/_github/librarian/lib/librarian/cli.rb:70:in `install'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/task.rb:27:in `run'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/invocation.rb:120:in `invoke_task'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor.rb:275:in `dispatch'
        from W:/tools/vagrant/embedded/lib/ruby/gems/1.9.1/gems/thor-0.15.2/lib/thor/base.rb:408:in `start'
        from D:/Repos/_github/librarian/lib/librarian/cli.rb:29:in `bin!'
        from D:/Repos/_github/librarian/bin/librarian-chef:7:in `<main>'
```

**Comment by tknerr** [comment]
Could it be that the file going to be moved is still open, e.g. as mentioned here?

https://github.com/codeodor/plupload-rails3/issues/15#issuecomment-2511967
https://github.com/codeodor/plupload-rails3/issues/15#issuecomment-2517370

**Comment by yfeldblum** [comment]
I'm not quite sure what's going on.

So far as I can tell, there are no open files at that point.

The `librarian-chef` process apparently has access to `C:/Users/tkn/AppData/Local/Temp/(randomly-generated-name)/apache2` because it has, right before the point where the exception was raised, just extracted the contents of the apache2 cookbook tarball into that directoy.

The `librarian-chef` process apparently has access to `W:/repo/my-chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/apache2/version-uri/3c9da46c37b6c22c7005d34bd6bc6df9`, because it has just finished caching tarballs and JSON files there.

**Comment by yfeldblum** [comment]
I pushed e59f5f1a87c7095277eaee67a70852dbc31ad3ad.

Can you try this again with the current master?

**Comment by tknerr** [comment]
Works like a charm! Thanks!

**Comment by yfeldblum** [comment]
Great!
