### ISSUE TITLE
missing git ref when run in git post-receive hook

### ISSUE THREAD

**Issue by jboxman** [applicationsonline/librarian#69]
While it runs fine manually, when run out of a git post-receive hook (of a different git repository than the local git repository referenced in the Cheffile below) I am experiencing this behavior:

```
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian]   [:git, "file:////var/lib/gitolite/repositories/bootstrap.git", {}]
[Librarian] Scheduling bootstrap (>= 0) <file:////var/lib/gitolite/repositories/bootstrap.git#master>
[Librarian] Scheduling apache2 (>= 0) <http://community.opscode.com/api/v1>
[Librarian] Scheduling database (>= 0) <http://community.opscode.com/api/v1>
[Librarian] Scheduling mysql (>= 0) <http://community.opscode.com/api/v1>
[Librarian] Scheduling yum (>= 0) <http://community.opscode.com/api/v1>
[Librarian] Resolving bootstrap (>= 0) <file:////var/lib/gitolite/repositories/bootstrap.git#master>
[Librarian]   No known prior constraints
[Librarian] Running `/usr/lib/git-core/git reset --hard --quiet` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
[Librarian] Running `/usr/lib/git-core/git rev-parse HEAD --quiet` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
[Librarian]   Checking manifests
[Librarian]     Checking bootstrap/0.0.1 <file:////var/lib/gitolite/repositories/bootstrap.git#master>
[Librarian]       Resolving apache2 (>= 0) <http://community.opscode.com/api/v1>
[Librarian]         No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/apache2 to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/apache2/metadata.json
[Librarian]         Checking manifests
[Librarian]           Checking apache2/1.1.8 <http://community.opscode.com/api/v1>
[Librarian]             Resolving database (>= 0) <http://community.opscode.com/api/v1>
[Librarian]               No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/database to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/database/metadata.json
[Librarian]               Checking manifests
[Librarian]                 Checking database/1.2.0 <http://community.opscode.com/api/v1>
[Librarian]                   Scheduling aws (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                   Scheduling mysql (>= 1.2.0) <http://community.opscode.com/api/v1>
[Librarian]                   Scheduling postgresql (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                   Scheduling xfs (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                   Resolving mysql (>= 0) <http://community.opscode.com/api/v1>
[Librarian]                     No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/mysql to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/mysql/metadata.json
[Librarian]                     Checking manifests
[Librarian]                       Checking mysql/1.2.4 <http://community.opscode.com/api/v1>
[Librarian]                         Scheduling openssl (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                         Resolving yum (>= 0) <http://community.opscode.com/api/v1>
[Librarian]                           No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/yum to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/yum/metadata.json
[Librarian]                           Checking manifests
[Librarian]                             Checking yum/0.5.2 <http://community.opscode.com/api/v1>
[Librarian]                               Resolving aws (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                 No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/aws to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/aws/metadata.json
[Librarian]                                 Checking manifests
[Librarian]                                   Checking aws/0.99.1 <http://community.opscode.com/api/v1>
[Librarian]                                     Resolving mysql (>= 1.2.0) <http://community.opscode.com/api/v1>
[Librarian]                                       Accords with all prior constraints
[Librarian]                                     Resolving postgresql (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                       No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/postgresql to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/postgresql/metadata.json
[Librarian]                                       Checking manifests
[Librarian]                                         Checking postgresql/0.99.4 <http://community.opscode.com/api/v1>
[Librarian]                                           Scheduling openssl (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                           Resolving xfs (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                             No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/xfs to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/xfs/metadata.json
[Librarian]                                             Checking manifests
[Librarian]                                               Checking xfs/1.0.0 <http://community.opscode.com/api/v1>
[Librarian]                                                 Resolving openssl (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                                   No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/openssl to /srv/cookbooks/rsync/testing/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/openssl/metadata.json
[Librarian]                                                   Checking manifests
[Librarian]                                                     Checking openssl/1.0.0 <http://community.opscode.com/api/v1>
[Librarian]                                                       Resolving openssl (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                                         Accords with all prior constraints
[Librarian]                                                       Resolved openssl (>= 0.0.0) <http://community.opscode.com/api/v1> at openssl/1.0.0 <http://community.opscode.com/api/v1>
[Librarian]                                                   Resolved openssl (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                                 Resolved xfs (>= 0.0.0) <http://community.opscode.com/api/v1> at xfs/1.0.0 <http://community.opscode.com/api/v1>
[Librarian]                                             Resolved xfs (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                           Resolved postgresql (>= 0.0.0) <http://community.opscode.com/api/v1> at postgresql/0.99.4 <http://community.opscode.com/api/v1>
[Librarian]                                       Resolved postgresql (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                     Resolved aws (>= 0.0.0) <http://community.opscode.com/api/v1> at aws/0.99.1 <http://community.opscode.com/api/v1>
[Librarian]                                 Resolved aws (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                               Resolved yum (>= 0) <http://community.opscode.com/api/v1> at yum/0.5.2 <http://community.opscode.com/api/v1>
[Librarian]                           Resolved yum (>= 0) <http://community.opscode.com/api/v1>
[Librarian]                         Resolved mysql (>= 0) <http://community.opscode.com/api/v1> at mysql/1.2.4 <http://community.opscode.com/api/v1>
[Librarian]                     Resolved mysql (>= 0) <http://community.opscode.com/api/v1>
[Librarian]                   Resolved database (>= 0) <http://community.opscode.com/api/v1> at database/1.2.0 <http://community.opscode.com/api/v1>
[Librarian]               Resolved database (>= 0) <http://community.opscode.com/api/v1>
[Librarian]             Resolved apache2 (>= 0) <http://community.opscode.com/api/v1> at apache2/1.1.8 <http://community.opscode.com/api/v1>
[Librarian]         Resolved apache2 (>= 0) <http://community.opscode.com/api/v1>
[Librarian]       Resolved bootstrap (>= 0) <file:////var/lib/gitolite/repositories/bootstrap.git#master> at bootstrap/0.0.1 <file:////var/lib/gitolite/repositories/bootstrap.git#master>
[Librarian]   Resolved bootstrap (>= 0) <file:////var/lib/gitolite/repositories/bootstrap.git#master>
[Librarian] Bouncing Cheffile.lock
/var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/lockfile/parser.rb:60:in `parse': Expected DEPENDENCIES topic! (StandardError)
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/lockfile.rb:25:in `load'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/action/resolve.rb:31:in `run'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/cli.rb:134:in `resolve!'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/cli.rb:69:in `install'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/task.rb:27:in `send'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/task.rb:27:in `run'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/invocation.rb:120:in `invoke_task'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor.rb:275:in `dispatch'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/base.rb:408:in `start'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/cli.rb:29:in `bin!'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/bin/librarian-chef:7
 from /var/lib/gems/1.8/bin/librarian-chef:19:in `load'
 from /var/lib/gems/1.8/bin/librarian-chef:19
```

The value of lines variable when it fails:

``` ruby
["  specs:", "    bootstrap (0.0.1)", "DEPENDENCIES", "  apache2 (>= 0)", "  bootstrap (>= 0)", "  database (>= 0)", "  mysql (>= 0)", "  yum (>= 0)"]
```

``` ruby
#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

if ENV['USER'] == 'gitolite'
    cookbook 'bootstrap',
            :git => 'file:////var/lib/gitolite/repositories/bootstrap.git'
end

cookbook 'apache2'
cookbook 'database'
cookbook 'mysql'
cookbook 'yum'

# https://github.com/gecos-team/cookbook-conf.git
```

And the lock file it would write:

``` ruby
SITE
  remote: http://community.opscode.com/api/v1
  specs:
    apache2 (1.1.8)
    aws (0.99.1)
    database (1.2.0)
      aws (>= 0.0.0)
      mysql (>= 1.2.0)
      postgresql (>= 0.0.0)
      xfs (>= 0.0.0)
    mysql (1.2.4)
      openssl (>= 0.0.0)
    openssl (1.0.0)
    postgresql (0.99.4)
      openssl (>= 0.0.0)
    xfs (1.0.0)
    yum (0.5.2)

GIT
  remote: file:////var/lib/gitolite/repositories/bootstrap.git
  ref: master
  sha: 
  specs:
    bootstrap (0.0.1)

DEPENDENCIES
  apache2 (>= 0)
  bootstrap (>= 0)
  database (>= 0)
  mysql (>= 0)
  yum (>= 0)
```

What should I do?

Thanks!

**Comment by yfeldblum** [comment]
Which version of librarian?

**Comment by jboxman** [comment]
Both 0.0.22 and e59f5f1a87c7095 from master.

**Comment by yfeldblum** [comment]
What operating system / platform?

**Comment by yfeldblum** [comment]
Any chance dcc0d18b4fe7b6e8d20057e07a4565307525d894 resolves it?

**Comment by jboxman** [comment]
Updated to dcc0d18.

It's Debian Squeeze.

ruby 1.8.7 (2010-08-16 patchlevel 302) [x86_64-linux]

For some reason, running under the git-hook environment, it can't seem to get a sha1.

```
[Librarian] Ruby Version: 1.8.7
[Librarian] Ruby Platform: x86_64-linux
[Librarian] Rubygems Version: 1.3.7
[Librarian] Librarian Version: 0.0.22
[Librarian] Librarian Adapter: chef
[Librarian] Project: /srv/cookbooks/rsync/testing
[Librarian] Specfile: Cheffile
[Librarian] Lockfile: Cheffile.lock
[Librarian] Pre-Cached Sources:
[Librarian]   [:git, "file:////var/lib/gitolite/repositories/bootstrap.git", {}]
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian] Post-Cached Sources:
[Librarian]   [:git, "file:////var/lib/gitolite/repositories/bootstrap.git", {}]
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian] The specfile is unchanged: nothing to do.
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:git, "file:////var/lib/gitolite/repositories/bootstrap.git", {}]
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian] Running `/usr/lib/git-core/git reset --hard --quiet` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
[Librarian] Running `/usr/lib/git-core/git rev-parse HEAD --quiet` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
[Librarian] Running `/usr/lib/git-core/git fetch origin --quiet` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
[Librarian] Running `/usr/lib/git-core/git fetch origin --quiet --tags` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
[Librarian] Running `/usr/lib/git-core/git remote` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
[Librarian] Running `/usr/lib/git-core/git branch -r` in tmp/librarian/cache/source/git/b6b937b3a6e0c5fe95d86aa674a3410b
/var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/source/git/repository.rb:106:in `hash_from': undefined method `include?' for nil:NilClass (NoMethodError)
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/source/git.rb:100:in `cache!'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/action/install.rb:45:in `cache_manifests'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/action/install.rb:44:in `each'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/action/install.rb:44:in `cache_manifests'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/action/install.rb:38:in `perform_installation'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/action/install.rb:12:in `run'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/cli.rb:136:in `install!'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/cli.rb:76:in `install'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/task.rb:27:in `send'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/task.rb:27:in `run'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/invocation.rb:120:in `invoke_task'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor.rb:275:in `dispatch'
 from /var/lib/gems/1.8/gems/thor-0.15.2/lib/thor/base.rb:408:in `start'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/lib/librarian/cli.rb:33:in `bin!'
 from /var/lib/gems/1.8/gems/librarian-0.0.22/bin/librarian-chef:7
 from /var/lib/gems/1.8/bin/librarian-chef:19:in `load'
 from /var/lib/gems/1.8/bin/librarian-chef:19
```

**Comment by yfeldblum** [comment]
Wondering if `GIT_DIR` is causing an issue.

See what happens with 606915525143c90669b4552fddd1fae6add82e1a.

**Comment by jboxman** [comment]
It's working great now.  Thank you for all your efforts on this!  Being able to easily use split cookbooks is such a pleasure!
