### ISSUE TITLE
Cannot install ruby-shadow from 37signals cookbooks

### ISSUE THREAD

**Issue by mguterl** [applicationsonline/librarian#7]
I'm trying to add the ruby-shadow cookbook to my chef-repo via my Cheffile.  I have added the following lines:

```
cookbook 'ruby-shadow', :git => 'git://github.com/37signals/37s_cookbooks.git'
```

When I run `librarian-chef install --verbose` I get the following output / errors:

```
pangaea ~/code/rm/chef-repo[master*]$ librarian-chef install --verbose
[Librarian] Precaching Sources:
[Librarian]   http://community.opscode.com/api/v1
[Librarian]   git://github.com/fnichol/chef-user.git#v0.2.0
[Librarian] Analyzing spec and lock:
[Librarian]   Removed:
[Librarian]   ExplicitRemoved:
[Librarian]   Added:
[Librarian]     ruby-shadow
[Librarian]   NonMatchingAdded:
[Librarian]     ruby-shadow
[Librarian]   Changed:
[Librarian]   DeepKeep:
[Librarian]     redis2
[Librarian]     sudo
[Librarian]     ufw
[Librarian]     user
[Librarian]   ShallowStrip:
[Librarian] Scheduling redis2 (>= 0) <http://community.opscode.com/api/v1>
[Librarian] Scheduling ufw (>= 0) <http://community.opscode.com/api/v1>
[Librarian] Scheduling sudo (>= 0) <http://community.opscode.com/api/v1>
[Librarian] Scheduling user (>= 0) <git://github.com/fnichol/chef-user.git#v0.2.0>
[Librarian] Scheduling ruby-shadow (>= 0) <git://github.com/37signals/37s_cookbooks.git#master>
[Librarian] Resolving redis2 (>= 0) <http://community.opscode.com/api/v1>
[Librarian]   Accords with all prior constraints
[Librarian] Resolving ufw (>= 0) <http://community.opscode.com/api/v1>
[Librarian]   Accords with all prior constraints
[Librarian] Resolving sudo (>= 0) <http://community.opscode.com/api/v1>
[Librarian]   Accords with all prior constraints
[Librarian] Resolving user (>= 0) <git://github.com/fnichol/chef-user.git#v0.2.0>
[Librarian]   Accords with all prior constraints
[Librarian] Resolving ruby-shadow (>= 0) <git://github.com/37signals/37s_cookbooks.git#master>
[Librarian]   No known prior constraints
[Librarian] Running `git clone git://github.com/37signals/37s_cookbooks.git . --quiet` in tmp/librarian/cache/source/git/441271418b19cd0b9aaf0503eb06472d
[Librarian] Running `git rev-parse HEAD --quiet` in tmp/librarian/cache/source/git/441271418b19cd0b9aaf0503eb06472d
[Librarian]     ->  edefbd17eeb8f25f6d42a01e7f207848fb23e49f
[Librarian] Running `git checkout master --quiet` in tmp/librarian/cache/source/git/441271418b19cd0b9aaf0503eb06472d
[Librarian] Running `git rev-parse HEAD --quiet` in tmp/librarian/cache/source/git/441271418b19cd0b9aaf0503eb06472d
[Librarian]     ->  edefbd17eeb8f25f6d42a01e7f207848fb23e49f
[Librarian]   Checking manifests
/Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/chef/manifest.rb:15:in `manifest_path': undefined method `join' for nil:NilClass (NoMethodError)
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/chef/manifest.rb:15:in `map'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/chef/manifest.rb:15:in `manifest_path'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/chef/source/local.rb:48:in `fetch_manifest!'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/chef/source/local.rb:44:in `manifest'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/chef/source/local.rb:52:in `fetch_version!'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/manifest.rb:34:in `version'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/manifest.rb:30:in `to_s'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:58:in `recursive_resolve'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:110:in `debug'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/helpers/debug.rb:28:in `debug'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/ui.rb:32:in `debug'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/helpers/debug.rb:28:in `debug'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:110:in `debug'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:58:in `recursive_resolve'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:56:in `each'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:56:in `recursive_resolve'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:104:in `scope'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:55:in `recursive_resolve'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:104:in `scope'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:38:in `recursive_resolve'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:23:in `resolve'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/resolver.rb:129:in `resolve'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian.rb:162:in `resolve!'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian.rb:103:in `install!'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/cli.rb:50:in `install'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/lib/librarian/cli.rb:15:in `bin!'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/gems/librarian-0.0.5/bin/librarian-chef:7
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/bin/librarian-chef:19:in `load'
    from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2011.03@rm-chef/bin/librarian-chef:19
```

**Comment by yfeldblum** [comment]
Thanks for the report.

I see that you have a Cheffile and a Cheffile.lock, and that you added ruby-shadow to your Cheffile and are attempting to update the Cheffile.lock and install the cookbook.

I am looking at [the ruby-shadow cookbook](https://github.com/cookbooks/ruby-shadow), but I do not see a `metadata.rb`.

Librarian-chef currently looks for a `metadata.rb` in each cookbook in order to identify if the directory it is looking at is a cookbook directory. Let me think whether there's something that can be done about that restriction.

**Comment by mguterl** [comment]
Ah, that makes sense.  I can probably work around that for this specific case.  Even if you can't work around the issue, would it be possible to fail fast in this case with a more descriptive error?

**Comment by yfeldblum** [comment]
I'm sure there's a good way to do this, but for now I've followed your second suggestion.

In this type of case, when the Chef adapter cannot find a metadata file: instead of failing fast with a `NoMethodError`, the it should now fail fast with a message saying that it could not find a metadata file.
