### ISSUE TITLE
Error when running librarian-chef install on a fresh Ubuntu 12.04/ruby 1.9.3

### ISSUE THREAD

**Issue by iafonov** [applicationsonline/librarian#82]
Librarian chef fails on a fresh Ubuntu 12.04

``` bash
vagrant@precise64:/project$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
vagrant@precise64:/project$ knife -v
Chef: 10.12.0
vagrant@precise64:/project$ librarian-chef version
librarian-0.0.23
```

Cheffile

``` ruby
site 'http://community.opscode.com/api/v1'

cookbook 'ntp'
```

Stack trace

``` ruby
vagrant@precise64:/project$ librarian-chef install
/usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/chef/manifest_reader.rb:18:in `read_manifest': undefined method `extname' for nil:NilClass (NoMethodError)
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/chef/source/site.rb:103:in `version_uri_manifest'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/chef/source/site.rb:94:in `version_manifest'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/chef/source/site.rb:59:in `version_dependencies'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/chef/source/site.rb:421:in `fetch_dependencies'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/manifest.rb:121:in `fetch_dependencies!'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/manifest.rb:113:in `fetched_dependencies'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/manifest.rb:77:in `dependencies'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:71:in `block (4 levels) in recursive_resolve'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:107:in `scope'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:68:in `block (3 levels) in recursive_resolve'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:64:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:64:in `block (2 levels) in recursive_resolve'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:107:in `scope'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:63:in `block in recursive_resolve'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:107:in `scope'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:46:in `recursive_resolve'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver/implementation.rb:24:in `resolve'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/resolver.rb:19:in `resolve'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/action/resolve.rb:25:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/cli.rb:139:in `resolve!'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/cli.rb:75:in `install'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.15.3/lib/thor/task.rb:27:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.15.3/lib/thor/invocation.rb:120:in `invoke_task'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.15.3/lib/thor.rb:275:in `dispatch'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.15.3/lib/thor/base.rb:425:in `start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/lib/librarian/cli.rb:33:in `bin!'
    from /usr/local/lib/ruby/gems/1.9.1/gems/librarian-0.0.23/bin/librarian-chef:7:in `<top (required)>'
    from /usr/local/bin/librarian-chef:23:in `load'
    from /usr/local/bin/librarian-chef:23:in `<main>'
```

**Comment by yfeldblum** [comment]
Is this still an issue?

**Comment by fson** [comment]
This happened to me today. For some reason the cache was corrupted and did not have one unpacked cookbook, just an empty folder. I removed the `tmp` folder, tried again and it worked.

**Comment by toxin20** [comment]
I have this problem as well. Emptying the cache didn't work either

**Comment by yfeldblum** [comment]
I cannot replicate with librarian-0.1.2 and librarian-chef-0.0.2.

**Comment by ghost** [comment]
I'm having the exact same problem, but when I use the command `vagrant up` with the config below. Any thoughts?

vagrant-1.8.5
librarian-0.1.2
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
berks version: 4.3.5
kitchen version: 1.10.2

Stack trace

```
==> default: Destroying VM and associated drives...
C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/dependency.rb:117:in 'cache_manifests!': undefined method 'manifests' for nil:NilClass (NoMethodError)
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/dependency.rb:113:in 'manifests'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in 'block in resolving_dependency_map_find_manifests'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in 'block (2 levels) in scope_resolving_dependency'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in 'block in scope_checking_manifests'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in 'scope'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in 'scope_checking_manifests'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in 'block in scope_resolving_dependency'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in 'scope'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in 'scope_resolving_dependency'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in 'resolving_dependency_map_find_manifests'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in 'recursive_resolve'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in 'resolve'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in 'resolve'
        from C:/Users/MyUser/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in 'run'
        from C:/Users/MyUser/.vagrant.d/gems/gems/vagrant-librarian-chef-nochef-0.2.0/lib/vagrant-librarian-chef/action/librarian_chef.rb:52:in 'resolve_and_install_cookbooks'
        from C:/Users/MyUser/.vagrant.d/gems/gems/vagrant-librarian-chef-nochef-0.2.0/lib/vagrant-librarian-chef/action/librarian_chef.rb:16:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/set_name.rb:50:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in 'busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in 'busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in 'busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_check_outdated.rb:78:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/config_validate.rb:25:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/match_mac_address.rb:19:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/discard_state.rb:15:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/import.rb:74:in 'import'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/import.rb:13:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/prepare_clone.rb:15:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/customize.rb:40:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in 'busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/config_validate.rb:25:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/handle_box.rb:56:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in 'block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in 'busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in 'busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in 'run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:225:in 'action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:200:in 'block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:561:in 'lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in 'call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in 'action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/batch_action.rb:82:in 'block (2 levels) in run'
```
