### ISSUE TITLE
`librarian-chef show` fails from the start

### ISSUE THREAD

**Issue by techtonik** [applicationsonline/librarian#85]
```
$ librarian-chef show
/usr/local/share/gems/gems/librarian-0.0.23/lib/librarian/lockfile.rb:29:in `read': No such file or directory - /home/workstation/chef/Cheffile.lock (Errno::ENOENT)
    from /usr/local/share/gems/gems/librarian-0.0.23/lib/librarian/lockfile.rb:29:in `read'
...
```

This could be more user friendly. I have not yet downloaded any cookbook.

**Comment by yfeldblum** [comment]
Fixed by e9c7885.
